[package]
name = "bolt"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "3.0", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
glob = "0.3.1"
regex = "1.10.5"
